name: Deploy to servers

on:
  push:
    branches: [main]

env:
  GITHUB: yes


jobs:

  verify:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version-file: go.mod

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get -y install xfonts-75dpi xfonts-base
        curl --silent --show-error --location --max-redirs 3 --fail --retry 3 --output wkhtmltopdf-linux-amd64.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltopdf-linux-amd64.deb
        sudo ldconfig
        rm wkhtmltopdf-linux-amd64.deb

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: $(go env GOPATH)/bin/staticcheck ./...

    # - name: Install golint
    #   run: go install golang.org/x/lint/golint@latest

    # - name: Run golint
    #   run: $(go env GOPATH)/bin/golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Build
      # run: go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o zimpe-back-go/server
      run: go build -v -o binary
